### ISSUE TITLE
Solution?

### ISSUE THREAD

**Issue by hassankhan98** [Ebryx/GitDump#3]
Fetching: refs/heads/master
Fetching: refs/remotes/origin/develop
Fetching: refs/remotes/origin/master
Fetching: refs/remotes/origin/step_develop
Fetching: refs/remotes/github/master
Fetching: objects/info/packs
Fetching: refs/remotes/origin/HEAD
Downloading Index File
Parsing Index File
Traceback (most recent call last):
  File "git-dump.py", line 99, in <module>
    jsonList = gin.parse_file(".git/index", pretty=False)
  File "/Users/cypher/tools/GitDump/gin.py", line 171, in parse_file
    for item in parse(arg, pretty=pretty):
  File "/Users/cypher/tools/GitDump/gin.py", line 25, in parse
    f = mmap.mmap(o.fileno(), 0, prot=mmap.PROT_READ)
ValueError: cannot mmap an empty file
Cyphers-MBP:GitDump cypher$

**Comment by elabdi** [comment]
I have the same problem ValueError: cannot mmap an empty file

**Comment by sh33lsh00k** [comment]
Sorry guys, there were a lot of bugs.
Updated the code for many bugs fix.
Also added threading.
